name: ci
on:
  push:
    branches: [ trunk ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Download release asset
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          gh release download xcc3 \
            --repo ${{ github.repository }} \
            --pattern 'xc8-v3.00-full-install-linux-x64-installer.run' \
            --output xc8-installer.run
      - name: Install XC8
        run: |
          chmod +x xc8-installer.run
          sudo ./xc8-installer.run --mode unattended --netservername aidan.gannon --"Add to PATH" 1
      - name: Add XC8 to PATH
        run: echo "/opt/microchip/xc8/v2.45/bin" >> $GITHUB_PATH
      - name: make
        run: |
          make